### ISSUE TITLE
Re-make using material design

### ISSUE THREAD

**Issue by kasperrt** [nixolas1/Zoff#107]
- [x] Fix file structure
- [x] Implement materialize http://materializecss.com/
- [x] Remake nochan
- [x] Remake main/index
- [ ] Color from thumb
- [x] Voting style
- [x] Disp Chan name
- [x] Fix search box
- [ ] pass box icon
- [x] disabled settings togglers style
- [x] style urls at bottom of footer
- [x] use minimized version of libs before launch
- [ ] (Rename Project, maybe fork? #108 )
- [ ] (Check security issues)

Will close #35 and #99

**Comment by nixolas1** [comment]
Making the site a bit more responsive (as in no lag on load) could also be fixed at the same time, by disabling blurring and optimizing cache usage.
