### ISSUE TITLE
Rework how list actions handle

### ISSUE THREAD

**Issue by kasperrt** [nixolas1/Zoff#113]
Only send song that was added, deleted or voted on from the server, instead of sending the full, sorted list back to all clients.

This will also mean sorting the lists clientside, instead of serverside. Lowers server load drastically.

**Comment by nixolas1** [comment]
FUkck u

On Fri, May 29, 2015 at 2:08 PM, KasperRT <notifications@github.com> wrote:

> Only send song that was added, deleted or voted on from the server,
> instead of sending the full, sorted list back to all clients.
>
> This will also mean sorting the lists clientside, instead of serverside.
> Lowers server load drastically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nixolas1/Zoff/issues/113>.
>



-- 
Nicolas Almagro Tonne
Nestsjef, Videokomiteen - Studentersamfundet i Trondhjem
Drifts- og utviklingskomitéen - Linjeforeningen Online, NTNU
+47 48 06 99 30
