### ISSUE TITLE
Placeholder on empty playlist

### ISSUE THREAD

**Issue by kasperrt** [nixolas1/Zoff#74]
Add something so the user doesn't think something is wrong when the list is empty. ("Remove" the looping of "trying" to change videos)

**Comment by nsystem1** [comment]
Check the new fix

**Comment by kasperrt** [comment]
What new fix? The player is still "looping" on error, and trying to play a song that isn't there.

The essence of this issue is that the player shouldn't say "Invalid parameters" or give out any errors. Instead it is suppose to have an overlay over the player, saying that the playlist is empty, and refrain from trying to start a new video that doesn't exist.

**Comment by nsystem1** [comment]
Well its just a temporary fix pending when overlay is fixed. Invalid parameters was due to invalid ID i included,that is fixed now.

Will work on the overlay

**Comment by kasperrt** [comment]
Found a way of fixing it from the backend, used you're method, and finished that in some way.

**Comment by nsystem1** [comment]
Great Work!
